import React, { useState } from 'react';
import styles from './TourListItem.module.css';
import cn from 'classnames';
// Import necessary icons or components for details like variant selector, price breakdown, booking panel

interface TourListItemProps {
  tourDate: any; // Replace with a more specific type later
}

const TourListItem: React.FC<TourListItemProps> = ({ tourDate }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  const handleToggleExpand = () => {
    setIsExpanded(!isExpanded);
    console.log(`Item ${tourDate.id} expansion toggled: ${!isExpanded}`);
  };

  return (
    <div id={tourDate.id} className={styles['list-item']}>
      <div className={styles['list-item__wrap']}>
        <div
          className={cn(
            styles['list-item__item'],
            isExpanded && styles.active,
          )}
          data-item-type={isExpanded ? "General Interaction" : "departure-expand"}
          data-item-name={isExpanded ? "departure-collapse" : "departure-expand"}
          data-item-departure={/* Add dynamic departure date here */ ''}
          onClick={handleToggleExpand}
        >
          {/* Tour Info - Summary View */}
          <div className={styles['tour-info']}> {/* This might be a separate component later */}
            <div className={styles['tour-info__container']}>
              <div className={styles['tour-info__container-body']}>

                {/* Tour Date (Departure) */}
                <div className={styles['tour-date']} style={{ flexBasis: '16.66%' }}> {/* This might be a separate component later */}
                  <div className={styles['info-header__empty']}></div> {/* Placeholder div */}
                  <p className={cn(styles['tour-date__day'], styles['text-paragraph-s'])} data-testid="genericText">{tourDate.day}</p>
                  <p className={cn(styles['tour-date__month-and-year'], styles['text-label-l'])} data-testid="genericText">{tourDate.date}</p>
                  {tourDate.details && (
                     <div className={styles['info-footer']}> {/* Further Information Link/Icon */}
                      <span data-testid="info-footer-icon" className={styles['icon-wrapper']}> {/* Icon will go here */}
                         {/* SVG for triangle down icon */} {/* Add SVG here or as component */}
                      </span>
                      <p className={cn(styles['info-footer__text'], styles['text-label-legend'])} data-testid="genericText">Further Information</p>
                     </div>
                  )}
                </div>

                {/* Tour Date (Return) */}
                 <div className={styles['tour-date']} style={{ flexBasis: '16.66%' }}> {/* This might be a separate component later */}
                  <div className={styles['info-header__empty']}></div> {/* Placeholder div */}
                  <p className={cn(styles['tour-date__day'], styles['text-paragraph-s'])} data-testid="genericText">{/* Return Day */}</p>
                  <p className={cn(styles['tour-date__month-and-year'], styles['text-label-l'])} data-testid="genericText">{/* Return Date */}</p>
                </div>

                {/* Departure Info (e.g., Standard tag) */}
                <div className={styles['departure-info']} style={{ flexBasis: '16.66%' }}> {/* This might be a separate component later */}
                   {tourDate.type && (\n                      <div className={styles['departure-info__wrapper']}> {/* Container for tag */}\n                         <div className={styles['departure-info__tag']} style={{ '--tag-component-background': '#ebff99', '--tag-component-text': '#000000' } as React.CSSProperties}> {/* Tag component/styles */}\n                           <p className={cn(styles['departure-info__tag-text'], styles['text-title-xxxxs'])} data-testid="genericText">{tourDate.type}</p>\n                         </div>\n                      </div>\n                   )}\n                   {/* Definite Departure text (conditionally rendered) */}\n                  <p className={cn(styles['definite-departure-info__short-text'], styles['text-paragraph-s'])} data-testid="genericText" data-optly-dc1df7d3-4c1a-41c8-b290-4dc4891d0ade="" style={{ display: 'none' }}>Definite Departure</p>\n                </div>\n
                {/* Group Size - Empty Placeholder */}
                <div className={styles['group-size-empty']} style={{ flexBasis: '16.66%' }}></div>\n
                {/* Offer Info (e.g., Last Minute Deal) */}
                <div className={styles.offer} style={{ flexBasis: '16.66%' }}> {/* This might be a separate component later */}
                   {tourDate.offer && (\n                      <p className={cn(styles['offer__discount'], styles['text-label-es'])} data-testid="genericText">{tourDate.offer}</p>\n                   )}\n                   {tourDate.oldPrice && tourDate.price && (\n                      <div className={styles['offer__wrapper']}> {/* Container for prices/discount tag */}\n                         <p className={cn(styles['offer__price-prefix'], styles['text-label-m'])} data-testid="genericText">Price</p>\n                         <p className={cn(styles['offer__price-old'], styles['text-strikethrough-m'])} data-testid="genericText">£{tourDate.oldPrice}</p>\n                         {tourDate.offerPercentage && (\n                            <div className={cn(styles.offer__percentage, styles.tag)}> {/* Discount Tag component/styles */}\n                              <div className={styles['tag__text-section']}> {/* Container for tag text */}\n                                <p className={cn(styles['text-tag-s'])} data-testid="genericText">{tourDate.offerPercentage}</p>\n                              </div>\n                            </div>\n                         )}\n                      </div>\n                   )}\n                </div>\n
                 {/* Price and Arrow */}\n                <div className={styles['tour-info__column']} style={{ flexBasis: '16.66%' }}> {/* This might be a separate component later */}\n                  <div className={styles.price}> {/* Price component/styles */}\n                    <div className={styles['price__top']}> {/* Container for current price/status */}\n                      <p className={cn(styles['price__top--price'], styles['text-comm-m'])} data-testid="genericText">{tourDate.status === 'Sold Out' ? 'Sold Out' : `£${tourDate.price}`}</p>\n                    </div>\n                  </div>\n                   {/* Expand/Collapse Arrow */}\n                  <div className={cn(styles['tour-info__container-arrow'], !isExpanded && styles['tour-info__container-arrow-hidden'])}>\n                    <span data-testid="tour-info-arrow" className={styles['icon-wrapper']} style={{ transform: `rotate(${isExpanded ? 90 : -90}deg)`, transition: '0.3s' }}> {/* Arrow Icon */}\n                      {/* SVG for arrow icon */} {/* Add SVG here or as component */}\n                    </span>\n                  </div>\n                </div>\n
              </div>\n            </div>\n          </div>\n        </div>\n
        {/* Tour Details - Expandable Section */}\n        <div className={cn(styles['tour-details'], styles['list-item__content'], isExpanded && styles.active)}>\n          {/* Content of the expandable details */}\n          {/* Variant Selector */}\n          <div className={styles['variant-selector']}> {/* This might be a separate component later */}\n             <div className=""> {/* Empty div from HTML */}\n                <div className={styles['variant-selector__row-header']}> {/* Header for variants */}\n                   <p className={cn(styles['text-label-l'])} data-testid="genericText">Start point</p>\n                </div>\n                 <div className={cn(styles['variant-selector__row-options'], styles['variant-selector__row-multiselect'])}> {/* Container for variant pills */}\n                   {/* Variant Pills will go here */}\n                    {/* Example Variant Pill */}\n                   {/*\n                   <button className={cn(styles['variant-pill'], styles['variant-pill--selected'])}> \n                     <div className={styles['variant-pill__header']}> \n                       <p className={cn(styles['variant-pill__title'], styles['text-title-xxxs'])} data-testid="genericText">London</p> \n                       <p className={cn(styles['variant-pill__subtitle'], styles['text-paragraph-s'])} data-testid="genericText">Wed 11 Jun 04:45</p> \n                     </div> \n                     <div className={styles['variant-pill__tail']}> \n                       <span className={styles['variant-pill__checkbox']}></span> \n                     </div> \n                   </button> \n                   */}\n                </div>\n             </div>\n          </div>\n
          {/* Final Step (Trip Title, Subtitle) */}\n          <div className={cn(styles['tour-details__final-step'], styles['tour-details__final-step--active'])}> {/* This might be a separate component later */}\n             <div className={styles['tour-details__trip-title-section']}> {/* Container for trip title/subtitle */}\n                <p className={cn(styles['tout-details__trip-title-section--title'], styles['text-title-s'])} data-testid="genericText">European Horizon</p>\n                <p className={cn(styles['tout-details__trip-title-section--subtitle'], styles['text-subtitle-xs'])} data-testid="genericText">Standard</p>\n             </div>\n
             {/* Tour Notes (Hidden by default) */}\n             <div className={cn(styles['tour-notes'], styles['tour-notes--hidden'])}> {/* This might be a separate component later */}\n                <div className={styles['tour-notes__top']}> {/* Top section of tour notes */}\n                   <div className={styles['tour-notes__top-left']}> {/* Icon and title */}\n                      <span className={styles['icon-wrapper']}> {/* Icon */}\n                         {/* SVG for eye filled icon */} {/* Add SVG here or as component */}\n                      </span>\n                      <p className={cn(styles['tour-notes__top-left-title'], styles['text-label-el'])} data-testid="genericText">Special Departures</p>\n                   </div>\n                </div>\n                {/* Tour Notes content will go here */}\n                {/* <div className={cn(styles['tour-notes__text-content'], styles['rich-text'], styles['text-paragraph-s'])} data-testid="genericText"> <p>...</p> </div> */}\n             </div>\n
             {/* Tour Details Bottom Section (Overview, Departure Alterations, Booking Conditions) */}\n             <div className={styles['tour-details__bottom-section']} data-testid="tour-details-bottom-section"> {/* This might be a separate component later */}\n                {/* Tour Overview (Departure/Return Dates and Info) */}\n                <div className={styles['tour-overview']}> {/* This might be a separate component later */}\n                   <div className={styles['tour-overview__top']}> {/* Top section of tour overview */}\n                      <div className={styles['definite-departure']}> {/* Definite departure text/tooltip */}\n                         <div className={styles.tooltip} data-testid="tooltip-trigger"> {/* Tooltip trigger */} {/* Tooltip content will go here */}\n                            <p className={cn(styles['definite-departure__text'], styles['text-label-l'])} data-testid="genericText" data-optly-dc1df7d3-4c1a-41c8-b290-4dc4891d0ade="" style={{ display: 'none' }}>This trip is a definite departure</p>\n                         </div>\n                      </div>\n                   </div>\n                   <div className={cn(styles['tour-overview__separtor'], styles['tour-overview__separtor--upper'])}></div> {/* Separator */}\n                   <div className={styles['tour-overview__bottom']}> {/* Bottom section of tour overview (Date details) */}\n                      <div className={styles['tour-date-details']}> {/* Container for date details */}\n                         {/* Date details (Day, Month, Year, Info) will go here */}\n                         {/* This section is complex and will likely need sub-components for dots and day info */}\n                      </div>\n                   </div>\n                </div>\n
                {/* Departure Alterations */}\n                <div className={styles['departure-alterations']}> {/* This might be a separate component later */}\n                   <div className={styles['departure-alterations__icon']}> {/* Icon */}\n                      <span data-testid="departure-alterations-icon" className={styles['icon-wrapper']}> {/* Icon */}\n                         {/* SVG for triangle down icon */} {/* Add SVG here or as component */}\n                      </span>\n                   </div>\n                   <div className={styles['departure-alterations__text']}> {/* Title and text content */}\n                      <p className={cn(styles['departure-alterations__title'], styles['text-label-m'])} data-testid="genericText">Further Information</p>\n                      {/* Rich text content will go here */}\n                      {/* <div className={cn(styles['departure-alterations__text-content'], styles['rich-text'], styles['text-paragraph-s'])} data-testid="genericText"><p>...</p></div> */}\n                   </div>\n                </div>\n
                <div className={styles['tour-overview__separtor']}></div> {/* Separator */}\n
                 {/* Booking Conditions */}\n                 <p className={cn(styles['tour-overview__booking-conditions'], styles['rich-text'], styles['text-label-s'])} data-testid="genericText"><p><em>Flights there and back again aren't included.</em></p></p>\n             </div>\n          </div>\n
          {/* Price Breakdown */}\n          <div data-testid="price-breakdown" className={styles['price-breakdown']}> {/* This might be a separate component later */}\n             {/* Discount Panel */}\n             <div data-testid="discount-panel" className={styles['discount-panel']}> {/* This might be a separate component later */}\n                <p className={cn(styles['discount-panel__title'], styles['text-label-l'])} data-testid="genericText">PRICE BREAKDOWN</p>\n                {/* Price Rows will go here */}\n                {/* Example Price Row */}\n                {/*\n                <div data-testid="price-row" className={cn(styles['price-row'])}> \n                   <div className={cn(styles['price-row__left'])}> \n                      <p className={cn(styles['price-row__left-title'], styles['text-paragraph-m'])} data-testid="genericText">Standard</p> \n                   </div> \n                   <div className={cn(styles['price-row__right'])}> \n                      <div className={cn(styles['price-description'], styles['price-row__right-old'], styles['price-description--price'])}> \n                         <div className={cn(styles['price-description__wrapper'])}> \n                            <div className={cn(styles['price-description__info'])}> \n                               <p className={cn(styles['price-description__price'], styles['text-strikethrough-s'])} data-testid="genericText">£1,575</p> \n                            </div> \n                         </div> \n                      </div> \n                      <p className={cn(styles['price-row__right-new'], styles['text-paragraph-m'])} data-testid="genericText">£1,260 </p> \n                   </div> \n                </div> \n                */}\n
                {/* Total Row (Savings) */}\n                {/*\n                <div data-testid="total-row" className={cn(styles['total-row'])}> \n                   <p className={cn(styles['total-row__title'], styles['text-label-l'])} data-testid="genericText">Total Savings</p> \n                   <p className={cn(styles['total-row__price'], styles['total-row__price--savings'], styles['text-label-el'])} data-testid="genericText">£315 </p> \n                </div> \n                */}\n
                {/* Additional Info Row (e.g., Last Minute Deal) */}\n                {/*\n                <div data-testid="additional-info-row" className={cn(styles['additional-info-row'])}> \n                   <span data-testid="additional-info-row-icon" className={cn(styles['icon-wrapper'])}> \n                      {/* SVG for label icon *\/}\n                   </span> \n                   <p className={cn(styles['additional-info-row__text'], styles['text-label-l'])} data-testid="genericText">Last Minute Deal</p> \n                </div> \n                */}\n             </div>\n          </div>\n
          {/* Booking Panel */}\n          <div data-testid="booking-panel" className={cn(styles['booking-panel'])}> {/* This might be a separate component later */}\n             <div className={cn(styles['booking-panel__top'])}> {/* Top section of booking panel */}\n                {/* Booking Title (Total Price, Subtitle) */}\n                <div data-testid="booking-title" className={cn(styles['booking-title'])}> {/* This might be a separate component later */}\n                   <p className={cn(styles['booking-title__text'], styles['text-title-xs'])} data-testid="genericText">Total Price</p>\n                   <p className={cn(styles['booking-title__subtitle'], styles['text-paragraph-xs'])} data-testid="genericText">Based on multishare room</p>\n                </div>\n
                {/* Booking Price */}\n                <div data-testid="booking-price" className={cn(styles['booking-price'])}> {/* This might be a separate component later */}\n                   {/* Old Price */}\n                   {/*\n                   <div className={cn(styles['price-description'], styles['booking-price__old'], styles['price-description--price'])}> \n                      <div className={cn(styles['price-description__wrapper'])}> \n                         <div className={cn(styles['price-description__info'])}> \n                            <p className={cn(styles['price-description__price'], styles['text-strikethrough-s'])} data-testid="genericText">£1,575</p> \n                         </div> \n                      </div> \n                   </div> \n                   */}\n                   {/* New Price */}\n                   <p className={cn(styles['booking-price__new'], styles['text-comm-xl'])} data-testid="genericText">£1,260</p>\n                </div>\n             </div>\n
             {/* Booking Buttons */}\n             <div className={cn(styles['booking-panel__buttons'])}> {/* Container for buttons */}\n                {/* Button components will go here */}\n                {/* Example Button */}\n                {/*\n                <a data-testid="btn" className={cn(styles.btn, styles['btn--L'], styles['booking-panel__button'], styles['btn-pr-booking'], styles['btn--icon-Left'])} target="_blank" href="#" rel="noopener noreferrer" title="CONTINUE" data-item-type="Booking Interest" data-item-name="book-now"> \n                   <p className={cn(styles['text-button-l'])} data-testid="genericText">CONTINUE</p> \n                </a> \n                */}\n             </div>\n          </div>\n        </div>\n      </div>\n    </div>
  );
};

export default TourListItem; 